# Generated by Django 3.2.4 on 2021-07-16 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=255)),
                ('middle', models.CharField(max_length=255)),
                ('bottom', models.CharField(max_length=255)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('recent_update', models.DateField(auto_now_add=True)),
                ('thumbnail', models.TextField(default='thumbnail_url')),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_id', to='main_app.photo')),
                ('middle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_id', to='main_app.photo')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_id', to='main_app.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('img_src', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
