# Generated by Django 3.2.4 on 2021-07-11 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=255)),
                ('middle', models.CharField(max_length=255)),
                ('bottom', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('is_public', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('recent_update', models.DateField()),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_image', to='main_app.slice')),
                ('middle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_image', to='main_app.slice')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_image', to='main_app.slice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
