# Generated by Django 3.2.4 on 2021-07-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_slice_id', to='main_app.slice'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='middle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_slice_id', to='main_app.slice'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_slice_id', to='main_app.slice'),
        ),
    ]
