# Generated by Django 3.2.4 on 2021-07-11 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20210711_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slice',
            new_name='Slices',
        ),
    ]
