# Generated by Django 3.2.4 on 2021-07-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210713_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_id', to='main_app.photo'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='middle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_id', to='main_app.photo'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_id', to='main_app.photo'),
        ),
    ]
