# Generated by Django 3.2.4 on 2021-07-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='thumbnail',
            field=models.TextField(default='thumbnail_url'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
